routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebController\ApplicationController;
use App\Http\Controllers\WebController\RecordsController;
use App\Http\Controllers\WebController\HomeController;
use App\Http\Controllers\WebController\ReportsController;
use App\Http\Controllers\WebController\FileSetupController;
use App\Http\Controllers\WebController\DashboardController;
use App\Http\Controllers\WebController\CollectionController;
use App\Http\Controllers\WebController\KioskController;
use App\Http\Controllers\Auth\LoginController;


// Filesetup //
use App\Http\Controllers\WebController\Filesetup\TTUController;
use App\Http\Controllers\WebController\Filesetup\OfficeController;
use App\Http\Controllers\WebController\Filesetup\SatelliteController;
use App\Http\Controllers\WebController\Filesetup\SignatoriesController;
use App\Http\Controllers\WebController\Filesetup\UsersController;
use App\Http\Controllers\WebController\Filesetup\CashierController;
use App\Http\Controllers\WebController\Filesetup\ShiftsController;
use App\Http\Controllers\WebController\Filesetup\ProvincialController;
use App\Http\Controllers\WebController\Filesetup\OSSCOController;
use App\Http\Controllers\WebController\Filesetup\AirlinesController;
use App\Http\Controllers\WebController\Filesetup\ReferenceController;
use App\Http\Controllers\WebController\Filesetup\ORCertificateController;





// End of Filesetup //
use Illuminate\Support\Facades\View;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::resource('/kiosk', KioskController::class);
Route::get('/kiosk-sm',[KioskController::class,'show_singlemultiple'])->name('kiosk.sm');
Route::get('/kiosk-single',[KioskController::class,'show_single'])->name('kiosk.single');
Route::get('/kiosk-multiple',[KioskController::class,'show_multiple'])->name('kiosk.multiple');
Route::post('/kiosk-validate',[KioskController::class,'validation'])->name('kiosk.validate');
Route::post('/kiosk-multiple-validate',[KioskController::class,'multiple_validation'])->name('kiosk.multiple-validate');
Route::get('/kiosk-qr/{id}',[KioskController::class,'show_qrcode'])->name('kiosk.show_qr');
Route::post('/kiosk-store',[KioskController::class,'store_multiple'])->name('kiosk.store_multiple');
Route::get('/kiosk-multiple-display/{id}',[KioskController::class,'display_multiple'])->name('kiosk.multiple-display');

Route::any('/tec_application/json', 'App\Http\Controllers\ApiController\ApplicationController@filter_tec_application_by');



Route::get('/', function () {
    return view('auth.login');
});   

// Route::get('/',[LoginController::class,'login_mode']);


Auth::routes();

// Route::middleware(['isSuperAdmin'])->group(function () {
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('/application', ApplicationController::class);
    Route::resource('/records', RecordsController::class);
    Route::resource('/home', HomeController::class);
    Route::resource('/reports', ReportsController::class);
    Route::resource('/filesetup', FileSetupController::class);
    Route::resource('/traveltaxunit', TTUController::class);
    Route::resource('/office_location', OfficeController::class);
    Route::resource('/satellite', SatelliteController::class);
    Route::resource('/signatories', SignatoriesController::class);
    Route::resource('/user_account', UsersController::class);
    Route::resource('/cashier', CashierController::class);
    Route::resource('/shifts', ShiftsController::class);
    Route::resource('/provincial', ProvincialController::class);
    Route::resource('/ossco', OSSCOController::class);
    Route::resource('/dashboard', DashboardController::class);
    Route::resource('/collection', CollectionController::class);
    Route::resource('/airlines', AirlinesController::class);
    Route::resource('/reference', ReferenceController::class);
    Route::resource('/certificate', ORCertificateController::class);











    Route::post('/print', [ReportsController::class,'print_application'])->name('reports.print');
    Route::get('/get_section/{id}', [ApplicationController::class,'getSectionDesc'])->name('getSD');
    Route::get('/view_application/{type}/{id}', [ApplicationController::class,'view_application'])->name('view_application');
    Route::get('/confirmation/{id}', [ApplicationController::class,'confirmation'])->name('confirmation_');
    Route::get('/payment/{id}/{cashier}', [ApplicationController::class,'payment_details'])->name('payment_');
    Route::post('/save_rtt', [ApplicationController::class,'save_rtt'])->name('rtt_save');
    Route::post('/save_fulltax', [ApplicationController::class,'save_fulltax'])->name('fulltax_save');
    Route::post('/save_usersettings', [ApplicationController::class,'save_usersettings'])->name('usettings_save');
    Route::get('/get_osreference', [ApplicationController::class,'getOnsiteReference']);
    Route::get('/get_sectwhere/{type}', [ApplicationController::class,'sectionWhere']);
    Route::get('/getrtt_amt/{section}/{class}', [ApplicationController::class,'getrtt_amt']);
    Route::get('/generate_cert/{id}/{type}', [ApplicationController::class,'generate_cert'])->name('generate_cert');
    Route::get('/load_traveltax', [TTUController::class,'load_traveltaxunit'])->name('load_ttu');
    Route::get('/load_office', [OfficeController::class,'load_office'])->name('load_office');
    Route::get('/load_satellite', [SatelliteController::class,'load_satellite'])->name('load_satellite');
    Route::get('/load_signatories', [SignatoriesController::class,'load_signatories'])->name('load_signatories');
    Route::get('/load_user_account', [UsersController::class,'load_user_account'])->name('load_user_account');
    Route::get('/load_cashier', [CashierController::class,'load_cashier'])->name('load_cashier');
    Route::get('/load_shifts', [ShiftsController::class,'load_shifts'])->name('load_shifts');
    Route::get('/load_provincial', [ProvincialController::class,'load_provincial'])->name('load_provincial');
    Route::get('/load_ossco', [OSSCOController::class,'load_ossco'])->name('load_ossco');
    Route::get('/load_airlines', [AirlinesController::class,'load_airlines'])->name('load_airlines');
    Route::get('/load_reference', [ReferenceController::class,'load_reference'])->name('load_reference');
    Route::get('/load_fs_certificate', [ORCertificateController::class,'load_fs_certificate'])->name('load_fs_certificate');
    Route::get('/get_settings/{id}', [ORCertificateController::class,'get_settings']);

    Route::get('/get_rtt_sections_by/{id}', [ApplicationController::class,'get_rtt_sections_by'])->name('get_rtt_sections_by');
    Route::get('/get_usettings', [HomeController::class,'get_usettings'])->name('get_usettings');
    Route::get('/get_kioskdetails/{id}', [KioskController::class,'get_kioskdetails'])->name('get_kioskdetails');
    Route::get('/onsite_print_or/{ref}', [ApplicationController::class,'onsite_print_or'])->name('onsite_print_or');
    Route::post('/save_payment_or', [ApplicationController::class,'save_payment_or'])->name('save_payment_or');


});

Route::get('/qr_code_ft/{id}/{file}', [ function ($id,$file) {
	$folder_path = storage_path('tieza/fulltax/qr-code/'.$id.'/'.$file);

	$explode_file = explode('.', $file);

	if(in_array($explode_file[1], ['png', 'jpg', 'jpeg']))
	{
	   	$content = 'image/jpeg';
	}
	elseif(in_array($explode_file[1], ['pdf']))
	{
	   	$content = 'application/pdf';
	}

	if(file_exists($folder_path)) return response()->file($folder_path, array('Content-Type' => $content));
	    
	abort(404);
}]);
// Route::middleware(['isRegularAdmin'])->prefix('supervisor')->group(function () {

//     Route::any('/home', [HomeController::class, 'index'])->name('home');
//     Route::resource('/application', ApplicationController::class);
//     Route::resource('/records', RecordsController::class);
//     Route::resource('/home', HomeController::class);
//     Route::resource('/reports', ReportsController::class);
//     Route::resource('/filesetup', FileSetupController::class);
//     Route::resource('/traveltaxunit', TTUController::class);
//     Route::resource('/office_location', OfficeController::class);
//     Route::resource('/satellite', SatelliteController::class);
//     Route::resource('/signatories', SignatoriesController::class);
//     Route::resource('/user_account', UsersController::class);

//     Route::post('/print', [ReportsController::class,'print_application'])->name('reports.print');
//     Route::get('/get_section/{id}', [ApplicationController::class,'getSectionDesc'])->name('getSD');
//     Route::get('/view_application/{type}/{id}', [ApplicationController::class,'view_application'])->name('view_application');
//     Route::post('/save_rtt', [ApplicationController::class,'save_rtt'])->name('rtt_save');
//     Route::post('/save_fulltax', [ApplicationController::class,'save_fulltax'])->name('fulltax_save');
//     Route::get('/generate_cert/{id}', [ApplicationController::class,'generate_cert'])->name('generate_cert');
//     Route::get('/load_traveltax', [TTUController::class,'load_traveltaxunit'])->name('load_ttu');
//     Route::get('/load_office', [OfficeController::class,'load_office'])->name('load_office');
//     Route::get('/load_satellite', [SatelliteController::class,'load_satellite'])->name('load_satellite');
//     Route::get('/load_signatories', [SignatoriesController::class,'load_signatories'])->name('load_signatories');
//     Route::get('/load_user_account', [UsersController::class,'load_user_account'])->name('load_user_account');

// });

app/Http/Controllers/WebController/FileSetupController.php
<?php

namespace App\Http\Controllers\WebController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FileSetupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = ['module' => 'application'];
        return view('filesetup.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/WebController/Filesetup/AirlinesController.php
<?php

namespace App\Http\Controllers\WebController\FileSetup;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Airlines;
use Yajra\DataTables\Facades\DataTables;
use Session;
class AirlinesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = ['module' => 'application'];
        return view('filesetup.airlines.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data = ['module' => 'application'];
        return view('filesetup.airlines.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // $code = $request->code;
        $name = $request->name;
        
        try {
            //code...
            $data = new Airlines;
            $data->name           =   $name;
            $data->created_by     =   auth()->user()->id;
            $data->save();
            return back()->with('success', 'Successfully saved!'); 

        } catch (\Throwable $th) {
            //throw $th;
            return back()->with('failed', $th); 

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $office = Airlines::find($id);
        $data = ['module' => 'application','val'=>$office];
        return view('filesetup.airlines.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        try {
            $data           =   Airlines::find($id);
            $data->name     =   $request->name;
            $data->update();
            return back()->with('success', 'Successfully updated!'); 

        } catch (\Throwable $th) {
            //throw $th;
            return back()->with('failed', $th); 
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        try {
            $data           =   Airlines::find($id);
            $data->name     =   $request->name;
            $data->update();
            return back()->with('success', 'Successfully updated!'); 

        } catch (\Throwable $th) {
            //throw $th;
            return back()->with('failed', $th); 
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function load_airlines()
    {
        try
        {
            $data = array();
            $data = Airlines::get();
        
            $datatables = Datatables::of($data)
            ->addColumn('action', function($data) {
                $start_tools = '<div class="tools">
                            <button type="button" data-toggle="dropdown" class="btn btn-secondary dropdown-toggle" aria-expanded="false"><i class="icon icon-left mdi mdi-settings-square"></i>Options<span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                            <div role="menu" class="dropdown-menu" x-placement="bottom-start">
                                <a href="'.route('airlines.show', $data->id).'" class="dropdown-item" >
                                    <i class="icon icon-left mdi mdi-eye"></i>View
                                </a>';
                $end_tools =  '</div></div>';

                return  $start_tools.$end_tools;
            });

            $rawColumns = ['action', 'name'];

        }
        catch(Exception $e)
        {
            info($e->getMessage());
            return response(['errors' => $e->getMessage()], 201);
        }
       
        return $datatables->rawColumns($rawColumns)->make(true);
    }
}

resources/views/filesetup/cashier/create.blade.php
@extends('filesetup.index')
@section('fs-content')
<h4><b> Cashier</b></h4>
<form action="{{route('cashier.store')}}" method="post">
    @csrf
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="code" >Code/Username</label>
            <input type="text" name="code" id="code" class="form-control form-control-sm" placeholder="Enter Code..">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="code" >Password</label>
            <input type="password" name="password" id="password" class="form-control form-control-sm" placeholder="Enter Code..">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="last_name">Lastname</label>
            <input type="text" name="last_name" id="name" class="form-control form-control-sm" placeholder="Enter Name..">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="first_name">Firstname</label>
            <input type="text" name="first_name" id="name" class="form-control form-control-sm" placeholder="Enter Name..">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="middle_name">Middlename</label>
            <input type="text" name="middle_name" id="name" class="form-control form-control-sm" placeholder="Enter Name..">
        </div>
    </div>
    {{-- <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="position">Position</label>
            <input type="text" name="position" id="name" class="form-control form-control-sm" placeholder="Enter Name..">
        </div>
    </div> --}}
    <div class="row py-2">
        <div class="col-12 col-md-6">
        <button type="submit" class="btn btn-primary btn-md">Save</button>
        <button type="button" class="btn btn-danger btn-md">Cancel</button>
        </div>
    </div>
</form>


@endsection
@section('scripts')
<script type="text/javascript"> 
$(document).ready(function()
{
    $('#cashier').addClass('active text-white');
})
</script>
@endsection

resources/views/filesetup/cashier/index.blade.php
@extends('filesetup.index')
@section('fs-content')
@include('layouts.auth-partials.datatables-css')
<div class="row py-2">
   <div class="col-12">
     <a href="{{route('cashier.create')}}" class="btn btn-primary text-white"><i class="mdi mdi-plus"></i> ADD</a>
     <table class="table table-striped bg-white table-hover table-fw-widget" id="tbl">
            <thead>
                <tr>
                    <td> </td>
                    <td width="20%">Code</td>
                    <td width="40%">Name</td>

                </tr>
            </thead>
            <tbody>
            </tbody>
        </table> 
    </div>
</div>

@endsection

@section('scripts')
@include('layouts.auth-partials.datatables-scripts')
<script type="text/javascript"> 
    $(document).ready(function () {
        
        App.init();
        App.dataTables();
        loadDatatable();
        $('#cashier').addClass('active text-white');
    });

    function loadDatatable()
    {
        
        @php
        $columns = array(['data' => 'action'],['data' => 'username'],['data' => 'name']);
        @endphp
        var url = '{{ route("load_cashier") }}';
        load_datables('#tbl', url ,{!! json_encode($columns) !!}, null);

    }
</script>
@endsection

resources/views/filesetup/cashier/show.blade.php
@extends('filesetup.index')
@section('fs-content')
<h4><b> Cashier</b></h4>
<form action="{{route('cashier.update',$val->id)}}" method="post">
    @method('put')
    @csrf
    <div class="row py-2">
        <div class="col-12 col-md-6">
        <button type="button" class="btn btn-primary btn-md" id="btn_edit"> <i class="mdi mdi-edit"></i> Edit</button>
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="code" >Code</label>
            <input type="text" name="code" id="code" class="form-control form-control-sm" value="{{$val->code}}" >
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="last_name">Lastname</label>
            <input type="text" name="last_name" id="name" class="form-control form-control-sm" value="{{$val->last_name}}">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="first_name">Firstname</label>
            <input type="text" name="first_name" id="name" class="form-control form-control-sm" value="{{$val->first_name}}">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="middle_name">Middlename</label>
            <input type="text" name="middle_name" id="name" class="form-control form-control-sm" value="{{$val->middle_name}}">
        </div>
    </div>
    <div class="row py-2">
        <div class="col-12 col-md-6">
            <label for="position">Position</label>
            <input type="text" name="position" id="name" class="form-control form-control-sm" value="{{$val->position}}">
        </div>
    </div>
    <div class="row btn-action py-2 d-none">
        <div class="col-12 col-md-6">
        <button type="submit" class="btn btn-primary btn-md">Save</button>
        <button type="button" id="btn_cancel" class="btn btn-danger btn-md">Cancel</button>
        </div>
    </div>
</form>
@endsection
@section('scripts')
<script type="text/javascript">
$(document).ready(function()
{
    $('#cashier').addClass('active text-white');
    $(':input').prop('readonly',true);
    $('#btn_edit').click(function()
    {
        $(':input').prop('readonly',false);
        $('.btn-action').removeClass('d-none');
        $('#btn_edit').hide();
    });
    $('#btn_cancel').click(function()
    {
        location.reload();

    });
});
</script>
@endsection