routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebController\ApplicationController;
use App\Http\Controllers\WebController\RecordsController;
use App\Http\Controllers\WebController\HomeController;
use App\Http\Controllers\WebController\ReportsController;
use App\Http\Controllers\WebController\FileSetupController;
use App\Http\Controllers\WebController\DashboardController;
use App\Http\Controllers\WebController\CollectionController;
use App\Http\Controllers\WebController\KioskController;
use App\Http\Controllers\Auth\LoginController;


// Filesetup //
use App\Http\Controllers\WebController\Filesetup\TTUController;
use App\Http\Controllers\WebController\Filesetup\OfficeController;
use App\Http\Controllers\WebController\Filesetup\SatelliteController;
use App\Http\Controllers\WebController\Filesetup\SignatoriesController;
use App\Http\Controllers\WebController\Filesetup\UsersController;
use App\Http\Controllers\WebController\Filesetup\CashierController;
use App\Http\Controllers\WebController\Filesetup\ShiftsController;
use App\Http\Controllers\WebController\Filesetup\ProvincialController;
use App\Http\Controllers\WebController\Filesetup\OSSCOController;
use App\Http\Controllers\WebController\Filesetup\AirlinesController;
use App\Http\Controllers\WebController\Filesetup\ReferenceController;
use App\Http\Controllers\WebController\Filesetup\ORCertificateController;





// End of Filesetup //
use Illuminate\Support\Facades\View;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::resource('/kiosk', KioskController::class);
Route::get('/kiosk-sm',[KioskController::class,'show_singlemultiple'])->name('kiosk.sm');
Route::get('/kiosk-single',[KioskController::class,'show_single'])->name('kiosk.single');
Route::get('/kiosk-multiple',[KioskController::class,'show_multiple'])->name('kiosk.multiple');
Route::post('/kiosk-validate',[KioskController::class,'validation'])->name('kiosk.validate');
Route::post('/kiosk-multiple-validate',[KioskController::class,'multiple_validation'])->name('kiosk.multiple-validate');
Route::get('/kiosk-qr/{id}',[KioskController::class,'show_qrcode'])->name('kiosk.show_qr');
Route::post('/kiosk-store',[KioskController::class,'store_multiple'])->name('kiosk.store_multiple');
Route::get('/kiosk-multiple-display/{id}',[KioskController::class,'display_multiple'])->name('kiosk.multiple-display');

Route::any('/tec_application/json', 'App\Http\Controllers\ApiController\ApplicationController@filter_tec_application_by');



Route::get('/', function () {
    return view('auth.login');
});   

// Route::get('/',[LoginController::class,'login_mode']);


Auth::routes();

// Route::middleware(['isSuperAdmin'])->group(function () {
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('/application', ApplicationController::class);
    Route::resource('/records', RecordsController::class);
    Route::resource('/home', HomeController::class);
    Route::resource('/reports', ReportsController::class);
    Route::resource('/filesetup', FileSetupController::class);
    Route::resource('/traveltaxunit', TTUController::class);
    Route::resource('/office_location', OfficeController::class);
    Route::resource('/satellite', SatelliteController::class);
    Route::resource('/signatories', SignatoriesController::class);
    Route::resource('/user_account', UsersController::class);
    Route::resource('/cashier', CashierController::class);
    Route::resource('/shifts', ShiftsController::class);
    Route::resource('/provincial', ProvincialController::class);
    Route::resource('/ossco', OSSCOController::class);
    Route::resource('/dashboard', DashboardController::class);
    Route::resource('/collection', CollectionController::class);
    Route::resource('/airlines', AirlinesController::class);
    Route::resource('/reference', ReferenceController::class);
    Route::resource('/certificate', ORCertificateController::class);











    Route::post('/print', [ReportsController::class,'print_application'])->name('reports.print');
    Route::get('/get_section/{id}', [ApplicationController::class,'getSectionDesc'])->name('getSD');
    Route::get('/view_application/{type}/{id}', [ApplicationController::class,'view_application'])->name('view_application');
    Route::get('/confirmation/{id}', [ApplicationController::class,'confirmation'])->name('confirmation_');
    Route::get('/payment/{id}/{cashier}', [ApplicationController::class,'payment_details'])->name('payment_');
    Route::post('/save_rtt', [ApplicationController::class,'save_rtt'])->name('rtt_save');
    Route::post('/save_fulltax', [ApplicationController::class,'save_fulltax'])->name('fulltax_save');
    Route::post('/save_usersettings', [ApplicationController::class,'save_usersettings'])->name('usettings_save');
    Route::get('/get_osreference', [ApplicationController::class,'getOnsiteReference']);
    Route::get('/get_sectwhere/{type}', [ApplicationController::class,'sectionWhere']);
    Route::get('/getrtt_amt/{section}/{class}', [ApplicationController::class,'getrtt_amt']);
    Route::get('/generate_cert/{id}/{type}', [ApplicationController::class,'generate_cert'])->name('generate_cert');
    Route::get('/load_traveltax', [TTUController::class,'load_traveltaxunit'])->name('load_ttu');
    Route::get('/load_office', [OfficeController::class,'load_office'])->name('load_office');
    Route::get('/load_satellite', [SatelliteController::class,'load_satellite'])->name('load_satellite');
    Route::get('/load_signatories', [SignatoriesController::class,'load_signatories'])->name('load_signatories');
    Route::get('/load_user_account', [UsersController::class,'load_user_account'])->name('load_user_account');
    Route::get('/load_cashier', [CashierController::class,'load_cashier'])->name('load_cashier');
    Route::get('/load_shifts', [ShiftsController::class,'load_shifts'])->name('load_shifts');
    Route::get('/load_provincial', [ProvincialController::class,'load_provincial'])->name('load_provincial');
    Route::get('/load_ossco', [OSSCOController::class,'load_ossco'])->name('load_ossco');
    Route::get('/load_airlines', [AirlinesController::class,'load_airlines'])->name('load_airlines');
    Route::get('/load_reference', [ReferenceController::class,'load_reference'])->name('load_reference');
    Route::get('/load_fs_certificate', [ORCertificateController::class,'load_fs_certificate'])->name('load_fs_certificate');
    Route::get('/get_settings/{id}', [ORCertificateController::class,'get_settings']);

    Route::get('/get_rtt_sections_by/{id}', [ApplicationController::class,'get_rtt_sections_by'])->name('get_rtt_sections_by');
    Route::get('/get_usettings', [HomeController::class,'get_usettings'])->name('get_usettings');
    Route::get('/get_kioskdetails/{id}', [KioskController::class,'get_kioskdetails'])->name('get_kioskdetails');
    Route::get('/onsite_print_or/{ref}', [ApplicationController::class,'onsite_print_or'])->name('onsite_print_or');
    Route::post('/save_payment_or', [ApplicationController::class,'save_payment_or'])->name('save_payment_or');


});

Route::get('/qr_code_ft/{id}/{file}', [ function ($id,$file) {
	$folder_path = storage_path('tieza/fulltax/qr-code/'.$id.'/'.$file);

	$explode_file = explode('.', $file);

	if(in_array($explode_file[1], ['png', 'jpg', 'jpeg']))
	{
	   	$content = 'image/jpeg';
	}
	elseif(in_array($explode_file[1], ['pdf']))
	{
	   	$content = 'application/pdf';
	}

	if(file_exists($folder_path)) return response()->file($folder_path, array('Content-Type' => $content));
	    
	abort(404);
}]);
// Route::middleware(['isRegularAdmin'])->prefix('supervisor')->group(function () {

//     Route::any('/home', [HomeController::class, 'index'])->name('home');
//     Route::resource('/application', ApplicationController::class);
//     Route::resource('/records', RecordsController::class);
//     Route::resource('/home', HomeController::class);
//     Route::resource('/reports', ReportsController::class);
//     Route::resource('/filesetup', FileSetupController::class);
//     Route::resource('/traveltaxunit', TTUController::class);
//     Route::resource('/office_location', OfficeController::class);
//     Route::resource('/satellite', SatelliteController::class);
//     Route::resource('/signatories', SignatoriesController::class);
//     Route::resource('/user_account', UsersController::class);

//     Route::post('/print', [ReportsController::class,'print_application'])->name('reports.print');
//     Route::get('/get_section/{id}', [ApplicationController::class,'getSectionDesc'])->name('getSD');
//     Route::get('/view_application/{type}/{id}', [ApplicationController::class,'view_application'])->name('view_application');
//     Route::post('/save_rtt', [ApplicationController::class,'save_rtt'])->name('rtt_save');
//     Route::post('/save_fulltax', [ApplicationController::class,'save_fulltax'])->name('fulltax_save');
//     Route::get('/generate_cert/{id}', [ApplicationController::class,'generate_cert'])->name('generate_cert');
//     Route::get('/load_traveltax', [TTUController::class,'load_traveltaxunit'])->name('load_ttu');
//     Route::get('/load_office', [OfficeController::class,'load_office'])->name('load_office');
//     Route::get('/load_satellite', [SatelliteController::class,'load_satellite'])->name('load_satellite');
//     Route::get('/load_signatories', [SignatoriesController::class,'load_signatories'])->name('load_signatories');
//     Route::get('/load_user_account', [UsersController::class,'load_user_account'])->name('load_user_account');

// });

app/Http/Controllers/WebController/KioskController.php
<?php

namespace App\Http\Controllers\WebController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\TT_KIOSK;
use App\Models\Countries;
use Carbon\Carbon;
use SimpleSoftwareIO\QrCode\Facades\QrCode; 
use Illuminate\Support\Facades\Storage;
use Crypt;
use Illuminate\Contracts\Encryption\DecryptException;
 
class KioskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('kiosk.welcome');
    }

    public function show_singlemultiple()
    {
        return view('kiosk.type');

    }
    public function show_single()
    {
        $countries = Countries::orderby('name','asc')->get();
        $data = ['countries'=>$countries];
        return view('kiosk.single-form',$data);
    }
    public function show_multiple()
    {
        $countries = Countries::orderby('name','asc')->get();
        $data = ['countries'=>$countries];
        return view('kiosk.multiple-form',$data);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function validation(Request $request)
    {
        $request->validate([
            'last_name' => 'required',
            'first_name' => 'required',
            'middle_name' => 'sometimes|nullable|max:50',
            'ticket_no' => 'required',
            'passport_no' => 'required',
            'mobile_no' => 'required',
            'email_address' => 'required',
            'destination' => 'required',
        ]);
        $data = ['details' => $request->all()];
        return view('kiosk.single-validate',$data);
    }
    public function multiple_validation(Request $request)
    {
        $data = ['details' => $request->all()];
        return view('kiosk.multiple-validate',$data);

    }
    public function store(Request $request)
    {
        try{
            $last_name      =  $request->last_name;
            $first_name     =  $request->first_name;
            $middle_name    =  $request->middle_name;
            $ticket_no      =  $request->ticket_no;
            $passport_no    =  $request->passport_no;
            $mobile_no      =  $request->mobile_no;
            $email_address  =  $request->email_address;
            $destination    =  $request->destination;


            $ttk = new TT_KIOSK;
            $ttk->ref_no            =   self::getKioskReference();
            $ttk->last_name         =   $last_name;
            $ttk->first_name        =   $first_name;
            $ttk->middle_name       =   $middle_name;
            $ttk->ticket_no         =   $ticket_no;
            $ttk->passport_no       =   $passport_no;
            $ttk->mobile_no         =   $mobile_no;
            $ttk->email_address     =   $email_address;
            $ttk->destination       =   $destination;
            if($ttk->save()) 
            {
                self::generate_qrcode($ttk->ref_no);
                $id = $ttk->ref_no;
                return redirect()->route('kiosk.show_qr',$id);
            }
            
            // 
            

        } catch (\Throwable $th) {
            
            throw $th;
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function generate_qrcode($id)
    {
        $f_tax = TT_KIOSK::where('ref_no',$id)->first();
        $qrcode_msg = $f_tax->ref_no;

         $pngImage = QrCode::format('png')->merge('img/tieza-logo.png', 0.3, true)
         ->size(500)->errorCorrection('H')
         ->generate($qrcode_msg);

         $output_file = '/tieza/fulltax/qr-code/'.$f_tax->ref_no.'/_qrcode.png';
         Storage::disk('storage')->put($output_file, $pngImage);

         return response()->json([
            'details' =>$f_tax ], 201);
    }
    public function show_qrcode($id)
    {
        // $_id = decrypt($id);
        $kiosk = TT_KIOSK::where('ref_no',$id)->first();
        
        $data = ['id' => $kiosk->ref_no,'kiosk' => $kiosk];
        
        return view('kiosk.qr_display',$data);
    }
    public function getKioskReference(){
        $kiosk = TT_KIOSK::orderBy('id','desc')->first();
      
        $last_ticket = $kiosk->ref_no ?? 0;
		$tick_date	= substr($last_ticket, 0, 10);
		$tick_date_now = date('Y-m-d');
		$tick_pre 	= "-APPKIOSK-";
		$tick_start = "000";
		$tick_num	= substr($last_ticket, 21, 24);
		
		if ($tick_date == $tick_date_now) { 
			$tick_d1 = $tick_date; 
			$tick_d2 = $tick_pre;
			$tick_dx = $tick_num + 1;
			$tick_d3 = str_pad($tick_dx, 3, '0', STR_PAD_LEFT);
		} else { 
			$tick_d1 = $tick_date_now;
		    $tick_d2 = $tick_pre;
			$tick_d3 = $tick_start;
		}
		 return $tick_dt = $tick_d1.$tick_d2.$tick_d3;
    }
    public function get_kioskdetails($id)
    {
        $details = TT_KIOSK::where('ref_no',$id)->get();
        $data = ['details'=>$details, 'count'=>count($details)];
        return $data;
    }
    public function store_multiple(Request $request)
    {
        $ref_no  =  self::getKioskReference();
        try{
            for ($i=0; $i < count($request->last_name) ; $i++) { 

            $last_name      =  $request['last_name'][$i];
            $first_name     =  $request['first_name'][$i];
            $middle_name    =  $request['middle_name'][$i];
            $ticket_no      =  $request['ticket_no'][$i];
            $passport_no    =  $request['passport_no'][$i];
            $mobile_no      =  $request['mobile_no'][$i];
            $email_address  =  $request['email_address'][$i];
            $destination    =  $request['destination'][$i];


            $ttk = new TT_KIOSK;
            $ttk->ref_no            =   $ref_no;
            $ttk->last_name         =   $last_name;
            $ttk->first_name        =   $first_name;
            $ttk->middle_name       =   $middle_name;
            $ttk->ticket_no         =   $ticket_no;
            $ttk->passport_no       =   $passport_no;
            $ttk->mobile_no         =   $mobile_no;
            $ttk->email_address     =   $email_address;
            $ttk->destination       =   $destination;
                if($ttk->save()) 
                {
                   
                }
            }
            self::generate_qrcode($ref_no);
            // $id = encrypt($ref_no);
            return redirect()->route('kiosk.show_qr',$ref_no);
        } catch (\Throwable $th) {
            throw $th;
        }
        
    }
    public function display_multiple($id)
    {
        $kiosk = TT_KIOSK::where('ref_no',$id)->get();
        $data = ['details'=>$kiosk,'module'=>'application'];
        return view('kiosk.multiple-display',$data);
    }
}

resources/views/kiosk/index.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
<style type="text/css">
        .event-background{
            background: url("img/bg-tiezadarker.png");
            background-position: center;
            background-size: cover;
            height: 100%;
            width: 100%;
        }
        .header-bgs{
            background: url("img/header-bg.jpeg");
            background-position: center;
            background-size: cover;
            height: 100%;
            width: 100%;
        }
</style>
@include('layouts.auth-partials.meta')
@yield('meta')
@include('layouts.auth-partials.css')

@yield('css')
@yield('employees_css')
<link rel="stylesheet" href="{{ asset('beagle-v1.7.1/src/assets/css/app.css') }}" type="text/css"/>
<div class="header-bgs ">
    <div class="container">
       <a href="/kiosk"> <img src="{{asset('img/tieza-logo2.png')}}"  class="p-2 mx-auto img-fluid logos"> </a>
    </div>
</div>
</head>
<body class="event-background">
    @include('layouts.auth-partials.kiosk-content') 
    @include('layouts.auth-partials.scripts')
    @yield('employees_scripts')
    @yield('scripts')
    <!-- <script src="{{ asset('js/custom.js')}}"></script> -->
</body>
</html>

resources/views/kiosk/multiple-display.blade.php
@extends('layouts.master-auth')
@section('css')
<style>
.color-navy{
    font-family:'Arial Black' !important;
    color:rgb(13, 25, 148) !important;
}
td{
  text-transform: uppercase;
}
</style>
@endsection
@section('content')
 <div class="text-center">
    <div class="row">
        <div class="col-12 col-lg-10 offset-lg-1">
          <div class="card card-contrast ">
            <div class="card-header card-header-contrast card-header-featured bg-primary text-left"><span class="text-white">Transaction Details</span></div>
            <div class="card-body">
                <form action="{{route('kiosk.store_multiple')}}" method="post"> 
                  @csrf
                  <div class="card-title">
                  
                  </div>
                  <div class="row">
                      <div class="col-12">
                        <table class="table table-bordered">
                          <thead class=" bg-secondary text-white "> 
                            <tr>
                                <th></th>
                                <th>Surname</th>
                                <th>Firstname</th>
                                <th>Middlename</th>
                                <th>Ticket No. / Reference No.</th>
                                <th>Passport No.</th>
                            </tr>
                        </thead>
                         <tbody>
                              @foreach ($details as $item)
                              <tr>
                                <td><div class="tools">
                                  <button type="button" data-toggle="dropdown" class="btn btn-secondary dropdown-toggle" aria-expanded="false"><i class="icon icon-left mdi mdi-settings-square"></i>Options<span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                                  <div role="menu" class="dropdown-menu" x-placement="bottom-start">
                                      <a href="{{route('application.index', ['type'=>'fulltax','id'=>encrypt($item->id)])}}" class="dropdown-item" >
                                          <i class="icon icon-left mdi mdi-money-box"></i>Full Tax
                                      </a>
                                      <a href="{{route('application.index', ['type'=>'exemption','id'=>encrypt($item->id)])}}" class="dropdown-item" >
                                          <i class="icon icon-left mdi mdi-money-off"></i>Exemption
                                      </a>
                                      <a href="{{route('application.index', ['type'=>'reduced','id'=>encrypt($item->id)])}}" class="dropdown-item" >
                                        <i class="icon icon-left mdi mdi-minus-circle-outline"></i>Reduced
                                      </a>
                                      <a href="{{route('application.index', ['type'=>'refund','id'=>encrypt($item->id)])}}" class="dropdown-item" >
                                        <i class="icon icon-left mdi mdi-undo"></i>Refund
                                      </a>
                                    </div></td>
                                <td><input type="hidden" name="last_name[]" value="{{$item->last_name}}">{{$item->last_name}}</td>
                                <td><input type="hidden" name="first_name[]" value="{{$item->first_name}}">{{$item->first_name}}</td>
                                <td><input type="hidden" name="middle_name[]" value="{{$item->first_name}}">{{$item->first_name}}</td>
                                <td><input type="hidden" name="ticket_no[]" value="{{$item->ticket_no}}">{{$item->ticket_no}}</td>
                                <td><input type="hidden" name="passport_no[]" value="{{$item->passport_no}}">{{$item->passport_no}}</td>
                              </tr>
                              @endforeach
                             
                               
                         </tbody>
                          </table>
                      </div>
                  </div>
                  <br>
                  
                </form>
            </div>
            <div class="card-footer card-footer-contrast text-muted bg-primary"></div>
          </div>
        </div>
      </div>
</div>

@endsection

resources/views/kiosk/qr_display.blade.php
@extends('kiosk.index')
@section('css')
<style>
.color-navy{
    font-family:'Arial Black' !important;
    color:rgb(13, 25, 148) !important;
    
}
.type_label 
{
    color:rgb(13, 25, 148) !important;
    font-weight: 900;
}
</style>
@endsection
@section('content')
 <div class="text-center">
    <p class="color-navy h1 p-3">TRAVEL TAX SERVICES</p>
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
          <div class="card card-contrast ">
            <div class="card-header card-header-contrast card-header-featured bg-primary text-center"><span class="text-white">{{$kiosk->ref_no}}</span></div>
            <div class="card-body">
                <img src="" alt="" id="img-qr" style="height:300px;width:300px">
            </div>
            <div class="card-footer card-footer-contrast text-muted bg-primary"></div>
            <div class="text-center"><h1><a href="{{route('kiosk.index')}}"> Back to Home</a></h1></div>  
        </div>
        </div>
      </div>
</div>

@endsection
@section('scripts')
<script type="text/javascript">
    $(document).ready(function()
    {
        $('.logos').addClass('d-none');
        var id = '{{$id}}';
        var url = "{{ url('/qr_code_ft/:id/_qrcode.png') }}";
        url = url.replace(':id',id);
        $('#img-qr').attr('src',url);
 
    });
</script>    

@endsection

resources/views/kiosk/single-validate.blade.php
@extends('kiosk.index')
@section('css')
<style>
.color-navy{
    font-family:'Arial Black' !important;
    color:rgb(13, 25, 148) !important;
}
td{
  text-transform: uppercase;
}
</style>
@endsection
@section('content')
 <div class="text-center">
    <p class="color-navy h1 p-3">TRAVEL TAX SERVICES</p>
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
          <div class="card card-contrast ">
            <div class="card-header card-header-contrast card-header-featured bg-primary text-left"><span class="text-white">Transaction Details Confirmation</span></div>
            <div class="card-body">
                <form action="{{route('kiosk.store')}}" method="post"> 
                  @csrf
                  <div class="card-title">
                    <u>Please confirm transaction below</u> 
                  </div>
                  <div class="row">
                      <div class="col-12">
                        <table class="table table-bordered">
                            <tr >
                              <td width="35%" class="bg-dark text-white">Surname</td>
                              <td width="65%"><b>{{ $details['last_name']}}</b>
                                <input type="hidden" name="last_name" id="" value="{{ $details['last_name']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Firstname</td>
                              <td ><b>{{ $details['first_name']}}</b>
                                <input type="hidden" name="first_name" id="" value="{{ $details['first_name']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Middlename</td>
                              <td ><b>{{ $details['middle_name']}}</b>
                                <input type="hidden" name="middle_name" id="" value="{{ $details['middle_name']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Mobile No.</td>
                              <td ><b>{{ $details['mobile_no']}}</b>
                                <input type="hidden" name="mobile_no" id="" value="{{ $details['mobile_no']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Email Address</td>
                              <td ><b>{{ $details['email_address']}}</b>
                                <input type="hidden" name="email_address" id="" value="{{ $details['email_address']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Destination</td>
                              <td ><b>{{ $details['destination_text']}}</b>
                                <input type="hidden" name="destination" id="" value="{{ $details['destination']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Ticket No./Reference No.</td>
                              <td ><b>{{ $details['ticket_no']}}</b>
                                <input type="hidden" name="ticket_no" id="" value="{{ $details['ticket_no']}}">
                              </td>
                            </tr>
                            <tr>
                              <td class="bg-dark text-white">Passport No.</td>
                              <td ><b>{{ $details['passport_no']}}</b>
                                <input type="hidden" name="passport_no" id="" value="{{ $details['passport_no']}}">
                              </td>
                            </tr>
                          </table>
                      </div>
                  </div>
                  <br>
                  <div class="row">
                    <div class="col-12 text-center">
                      <a href="#" class="">*If incorrect click CANCEL, then edit the details to correct.</a>
                    </div>
                  </div>
                  <br>
                  <div class="row text-center"> 
                    <div class="col-6 col-md-4 text-right mt-2">
                        <button type="button" class="btn btn-primary btn-xl w-50" onclick="history.back()"> < Cancel </button>
                    </div>
                    <div class="col-6 offset-md-4 col-md-4 text-left py-2">
                        <button type="submit" class="btn btn-primary btn-xl w-50"> Next > </button>
                    </div>
                  </div>
                </form>
            </div>
            <div class="card-footer card-footer-contrast text-muted bg-primary"></div>
          </div>
        </div>
      </div>
</div>

@endsection

resources/views/kiosk/type.blade.php
@extends('kiosk.index')
@section('css')
<style>
.color-navy{
    font-family:'Arial Black' !important;
    color:rgb(13, 25, 148) !important;
    
}
.type_label 
{
    color:rgb(13, 25, 148) !important;
    font-weight: 900;
}
</style>
@endsection
@section('content')
 <div class="text-center">
    <p class="color-navy h1 p-3">TRAVEL TAX SERVICES</p>
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
          <div class="card card-contrast ">
            <div class="card-header card-header-contrast card-header-featured bg-primary text-left"><span class="text-white">Type of Transaction</span></div>
            <div class="card-body">
                <br><br>
                <div class="row py-4">
                    <div class=" col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 offset-xl-3">
                        <button type="button" class="btn btn-dark btn-block btn-xl p-1" onclick="window.location= '{{route('kiosk.single')}}'"><span class="h3"><i class="mdi mdi-account-add"></i> SINGLE</span></button>
                    </div>
                </div>
                <div class="row py-2">
                    <div class=" col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 offset-xl-3">
                        <button type="button" class="btn btn-dark btn-block btn-xl p-1" onclick="window.location= '{{route('kiosk.multiple')}}'"><span class="h3"><i class="mdi mdi-accounts-add"></i> MULTIPLE</span></button>
                    </div>
                </div>
                <div class="row py-4 type_label">
                    <div class=" col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 offset-xl-3">
                        <p>For Full Tax multiple transaction maximum of 5 pax per transaction</p>
                    </div>
                </div>

            </div>
            <div class="card-footer card-footer-contrast text-muted bg-primary"></div>
          </div>
        </div>
    </div>
</div>

@endsection